//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cloth
    {
        public int CId { get; set; }

        [Required(ErrorMessage = "Please select product's gender")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Please select product's category")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Please select product's condition")]
        public string Condition { get; set; }

        [Required(ErrorMessage = "Please enter product's color")]
        [StringLength(15, ErrorMessage = "Please do not enter more than 15 characters")]
        public string Color { get; set; }

        [Required(ErrorMessage = "Please select product's size")]
        public string Size { get; set; }

        [Required(ErrorMessage = "Please enter product's brand")]
        [StringLength(30, ErrorMessage = "Please do not enter more than 30 characters")]
        public string Brand { get; set; }

        [Required(ErrorMessage = "Please enter a location of product")]
        [StringLength(100, ErrorMessage = "Please do not enter more than 100 characters")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Please enter product's price")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Price must be in the format dollars.cents")]
        [Range(0, 9999999999.99, ErrorMessage = "Out of Range - Please check the price again")]
        public Nullable<decimal> Price { get; set; }

        [Display(Name = "Product Image")]
        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif)$", ErrorMessage = "Only Image files allowed.")]
        public string Image { get; set; }
    }
}
