//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerProduct
    {
        public int SPID { get; set; }
        public int SID { get; set; }
        public int CID { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
